# make_fixture.py  --  generate the committed test fixtures.
#
# Run by hand, never by tests\build.bat and never by CI:
#
#     py -3 tests\make_fixture.py
#
# It writes tests\fixture_msml.h, tests\fixture_lzma.h and tests\fixture_mtv.h,
# which are committed. Re-run and commit the result if a fixture needs to grow
# a case.
#
# WHY THE BYTES ARE COMMITTED RATHER THAN MADE AT RUN TIME
#
# The build deliberately has no compressor of any kind. miniz comes in with
# MINIZ_NO_DEFLATE_APIS, and of the LZMA SDK only the decoder is vendored --
# 39 KB of the 400-odd files in the archive. So a harness that wants a
# compressed stream to read cannot make one; it has to be handed the bytes.
# That is a good property to keep, and this script is the price of it.
#
# THE FIXTURES ARE SYNTHETIC ON PURPOSE
#
# A slice of the real momentum\_cache, or a real demo, would be simpler and is
# not an option: both are other people's work with real ids in them, and the
# repository already refuses to carry anything of that shape (see .gitignore's
# reasoning about demos). Everything below is invented, and chosen to hit the
# paths that are otherwise only reachable on a machine with a game installed.

import json
import lzma
import math
import os
import sys
import zlib

HERE = os.path.dirname(os.path.abspath(__file__))


# ---------------------------------------------------------------------------
# Writing a header
# ---------------------------------------------------------------------------

def carray(name, blob):
    out = ["static const unsigned char %s[%d] = {" % (name, len(blob))]
    for i in range(0, len(blob), 12):
        out.append("    %s," % ", ".join("0x%02x" % b for b in blob[i:i + 12]))
    out.append("};")
    return "\n".join(out)


def write_header(name, guard, why, parts):
    path = os.path.join(HERE, name)
    body = ["// %s  --  generated by tests\\make_fixture.py. Do not hand-edit." % name,
            "//"]
    body += ["// " + line if line else "//" for line in why.strip().split("\n")]
    body += ["", "#ifndef %s" % guard, "#define %s" % guard, ""]
    for part in parts:
        body.append(part)
        body.append("")
    body += ["#endif // %s" % guard, ""]
    with open(path, "w", encoding="utf-8", newline="\n") as f:
        f.write("\n".join(body))
    print("wrote %s" % path)


# ---------------------------------------------------------------------------
# The map cache
# ---------------------------------------------------------------------------
#
#   - "tier": null, which a submitted map has until somebody rates it
#   - an id that is a JSON float, which the reference skips because it tests
#     isinstance(mid, int) and 265.0 is not one
#   - a tier on a trackType 1 board, which must NOT become the map's tier
#   - gamemodes listed out of order, which must come out sorted
#   - the same map name in both files, where the later file has to win
#   - a non-ASCII name, which must come out as the same UTF-8 bytes
#   - an object-with-"maps" file rather than a bare array, the branch the
#     reference keeps for a shape we have never actually met

APPROVED = [
    {"id": 383, "name": "bhop_landmark2",
     "leaderboards": [
         {"gamemode": 2, "trackType": 0, "trackNum": 1, "tier": 2},
         {"gamemode": 1, "trackType": 0, "trackNum": 1, "tier": 2},
         {"gamemode": 2, "trackType": 1, "trackNum": 1, "tier": 7},
     ]},
    # Overwritten by the submission file below: this is the stale copy.
    {"id": 111, "name": "surf_overlap",
     "leaderboards": [{"gamemode": 1, "trackType": 0, "trackNum": 1, "tier": 1}]},
    # No leaderboards at all: tier 0, no modes, and still a valid row.
    {"id": 7, "name": "ahop_bare", "leaderboards": []},
    # Not an int id. Skipped entirely, as isinstance(mid, int) skips it.
    {"id": 265.0, "name": "surf_floatid",
     "leaderboards": [{"gamemode": 1, "trackType": 0, "trackNum": 1, "tier": 3}]},
]

SUBMISSION = {"maps": [
    # Wins over the approved copy above, and is therefore NOT approved.
    {"id": 112, "name": "surf_overlap",
     "leaderboards": [{"gamemode": 1, "trackType": 0, "trackNum": 1, "tier": 5}]},
    # Unrated, which is null rather than absent.
    {"id": 1816, "name": "bhop_luvinox",
     "leaderboards": [{"gamemode": 2, "trackType": 0, "trackNum": 1,
                       "tier": None}]},
    # Modes deliberately descending in the file; the index is sorted.
    {"id": 900, "name": "surf_modes",
     "leaderboards": [
         {"gamemode": 12, "trackType": 0, "trackNum": 1, "tier": 4},
         {"gamemode": 3,  "trackType": 0, "trackNum": 1, "tier": 4},
         {"gamemode": 7,  "trackType": 2, "trackNum": 1, "tier": 9},
     ]},
    {"id": 901, "name": "surf_ümläut",
     "leaderboards": [{"gamemode": 1, "trackType": 0, "trackNum": 1, "tier": 6}]},
]}


def msml(obj):
    """MSML, u32 decompressed size, u32 map count, then a raw zlib stream."""
    maps = obj if isinstance(obj, list) else obj["maps"]
    body = json.dumps(obj, separators=(",", ":"), ensure_ascii=False)
    body = body.encode("utf-8")
    out = bytearray(b"MSML")
    out += len(body).to_bytes(4, "little")
    out += len(maps).to_bytes(4, "little")
    out += zlib.compress(body, 9)
    return bytes(out)


# ---------------------------------------------------------------------------
# A payload worth compressing
# ---------------------------------------------------------------------------
#
# Written as a formula rather than as bytes so that the committed header holds
# only the COMPRESSED stream. The harness computes the expected output with the
# same twelve lines and compares, which is what makes "the decoder produced the
# right bytes" a real assertion rather than "the decoder produced the bytes
# next to it in the same file".
#
# It has to be worth compressing in the specific ways the decoder can get
# wrong, so it is three things interleaved: literals it cannot predict, short
# runs of one byte, and matches a thousand bytes back. A decoder that mishandles
# long distances passes on noise alone.
#
# Keep in step with Payload() in tests\test_lzma.cpp and tests\test_mtv.cpp.

def payload(n):
    out = bytearray()
    s = 12345
    for i in range(n):
        s = (s * 1664525 + 1013904223) & 0xFFFFFFFF
        if i >= 1000 and (i // 137) % 3 == 0:
            out.append(out[i - 1000])
        elif (i // 61) % 5 == 0:
            out.append(0x41)
        else:
            out.append((s >> 24) & 0xFF)
    return bytes(out)


def valve_lzma(data, lc=3, lp=0, pb=2, dict_size=1 << 16):
    """The five property bytes and a raw LZMA1 stream, as a .mtv carries them."""
    filt = [{"id": lzma.FILTER_LZMA1, "lc": lc, "lp": lp, "pb": pb,
             "dict_size": dict_size}]
    c = lzma.LZMACompressor(format=lzma.FORMAT_RAW, filters=filt)
    comp = c.compress(data) + c.flush()

    props = bytes([(pb * 5 + lp) * 9 + lc]) + dict_size.to_bytes(4, "little")

    # Decode it back exactly the way wrpath_extract.py's decompress_body does,
    # so a fixture that the reference cannot read never reaches the repository.
    d = lzma.LZMADecompressor(format=lzma.FORMAT_RAW, filters=filt)
    back = d.decompress(comp, len(data))
    assert back == data, "fixture does not round-trip through the reference"
    return props, comp


def valve_zstd(data):
    """One zstd frame, as a .mtv carries them -- which is NOT as it carries an
    LZMA body. There is no seventeen-byte Valve header on this one: the frame
    magic sits where the LZMA container's "LZMA" tag would be, and the frame
    declares its own content size, which is the only reason a one-shot decoder
    can be used at all on either side.

    Needs the `zstandard` package, which is the same dependency the reference
    implementation has and states at wrpath_extract.py's import. Everything else
    in this file runs on the standard library alone."""
    try:
        import zstandard
    except ImportError:
        raise SystemExit(
            "the zstd fixture needs the 'zstandard' package (pip install "
            "zstandard). It is the same package tests\\reference\\"
            "wrpath_extract.py imports.")

    # write_content_size, explicitly, because the ENTIRE zstd path on both sides
    # depends on it: ZstdDecompressor().decompress() raises without a declared
    # size, and WrMtvZstdSize refuses with "zstd frame does not declare its
    # size". It is the default here, and a fixture must not rest on a default
    # that decides whether the thing under test can run.
    frame = zstandard.ZstdCompressor(level=3,
                                     write_content_size=True).compress(data)

    # The reference's own call, so a fixture it cannot read never reaches the
    # repository -- the same guard valve_lzma has.
    back = zstandard.ZstdDecompressor().decompress(frame)
    assert back == data, "fixture does not round-trip through the reference"
    assert frame[:4] == b"\x28\xb5\x2f\xfd", frame[:4].hex()
    return frame


# ---------------------------------------------------------------------------
# A demo
# ---------------------------------------------------------------------------
#
# The whole container, at both of the JSON offsets seen in the wild. The two
# differ by one byte of padding, which is the entire reason the reference
# locates the blob by scanning instead of reading it from a constant -- so a
# fixture that only had one of them would not test the thing the scan exists
# for.
#
# The run-stats JSON is deliberately FLAT, with no nested object, so that the
# first '{' at or after 0xB0 is the real one. The compressed body begins inside
# the same window and contains braces of its own, which is true of every real
# demo too -- the locator's job is to stop at the first one that validates, and
# a fixture where no other candidate existed would not be asking it to.

MTV_MAP = "surf_fixture"
MTV_HASH = "0123456789abcdef0123456789abcdef01234567"
MTV_PLAYER = "fixture player"
MTV_STEAMID = 0x0110000112345678
MTV_DATE_MS = 1700000000123
MTV_TICKS = 4083
MTV_BODY_BYTES = 4096

MTV_JSON = ('{"maxHorizontalSpeed":2500.5,"effectiveStartVelocity":320.25,'
            '"jumps":41,"strafes":812,"note":"synthetic, see make_fixture.py"}')


def mtv(json_at, codec="lzma"):
    import struct
    head = bytearray(b"\0" * json_at)
    head[0:4] = b"MMTV"
    struct.pack_into("<I", head, 0x04, 2)
    struct.pack_into("<q", head, 0x08, MTV_DATE_MS)
    head[0x10:0x10 + len(MTV_MAP)] = MTV_MAP.encode()
    head[0x50:0x50 + len(MTV_HASH)] = MTV_HASH.encode()
    head[0x79] = 1                                  # gamemode: surf
    struct.pack_into("<f", head, 0x7B, 0.015)
    struct.pack_into("<Q", head, 0x7F, MTV_STEAMID)
    head[0x87:0x87 + len(MTV_PLAYER)] = MTV_PLAYER.encode()
    head[0xA7] = 2                                  # track type: bonus
    head[0xA8] = 3                                  # track num
    struct.pack_into("<d", head, 0xA9, 61.25)
    struct.pack_into("<I", head, 0xB1, MTV_TICKS)

    blob = MTV_JSON.encode()
    struct.pack_into("<I", head, json_at - 4, len(blob))

    data = payload(MTV_BODY_BYTES)

    out = bytearray(head)
    out += blob
    if codec == "zstd":
        # Everything the LZMA arm needs a container for, the frame carries. So
        # this really is the whole of the difference: the tag and the twenty-two
        # bytes behind it are gone, and the body starts at bodyOff.
        out += valve_zstd(data)
    else:
        props, comp = valve_lzma(data)
        out += b"LZMA"
        out += struct.pack("<II", len(data), len(comp))
        out += props
        out += comp

    # The promises the harness is written against. Note what is NOT promised:
    # that there is only one '{' in the window. The compressed body starts well
    # before 0x200 and a compressed stream contains whatever bytes it contains,
    # exactly as a real demo's does. What matters is that the FIRST brace at or
    # after 0xB0 is the real one, so the locator stops on it and the padding
    # before it holds none.
    assert len(out) >= 0x200
    assert out.index(b"{", 0xB0) == json_at
    return bytes(out)


# ---------------------------------------------------------------------------
# A whole demo, with a path in it
# ---------------------------------------------------------------------------
#
# Everything above is one layer of the pipeline. This is all of them at once:
# a container holding a Valve-LZMA body that really does contain a route, and
# beside it the .wrpath THE REFERENCE PRODUCES FROM IT, byte for byte.
#
# WHY THIS EXISTS WHEN EVERY LAYER IS ALREADY TESTED
#
# test_mtv reads the container. test_lzma decodes a stream. test_dp scans and
# runs the dynamic program over a body it builds itself. test_wrpath writes a
# file and reads it back. Each of those is a good test and none of them would
# notice if the four were wired together wrongly -- a body handed over with the
# header's 17 container bytes still on the front, a tick interval read from the
# wrong field, markers anchored against the wrong point list. Those are seam
# bugs, and seams are exactly what a per-layer harness cannot see.
#
# The 6,249-demo parity run does see them, and it is the real proof. It also
# needs a game install, a demo library and a Python interpreter, which means it
# runs on one machine in the world and never in CI. This is the part of it that
# fits in 30 KB of committed C: one demo, one expected answer, on every push.
#
# WHY THE ANSWER COMES FROM THE REFERENCE AND NOT FROM THIS SCRIPT
#
# Because a golden that this file computed would only ever prove that two of my
# programs agree. The bytes below came out of wrpath_extract.py, which is the
# thing the port is a port OF, so a difference is a real difference.
#
# The path itself is a gentle helix -- the same shape test_dp plants, for the
# same reasons, and it is worth restating one of them: the filler is 0xFF, and
# a word of all ones has a biased exponent of 255, outside the [117, 141] the
# scan admits. So nothing in the filler can be mistaken for a coordinate and
# every candidate found is one put there on purpose.

E2E_POINTS = 200
E2E_STRIDE = 32                 # bytes between planted triples
E2E_BODY = 8192
E2E_TICKS = 210                 # > points, so coverage is 95.2% and not a round 100
E2E_DT = 0.015
E2E_RUN_TIME = 3.0              # E2E_POINTS * E2E_DT exactly
E2E_START_AT = 20               # which point effectiveStartVelocity fingerprints
E2E_MARKER_AT = 100             # ... and which one the one split marker does

E2E_MAP = "surf_synthetic"
E2E_STEM = "e2e"
E2E_STEAMID = 0x0110000112345678
E2E_FAKE_NOW = "1700000000"


def e2e_points():
    """The planted trajectory, as float32 widened to double -- which is what
    the extractor gets back, because struct.unpack('<3f') widens."""
    import struct
    pts = []
    for i in range(E2E_POINTS):
        t = i * 0.02
        bump = 30.0 if i >= E2E_POINTS // 2 else 0.0
        xyz = (2000.0 + 300.0 * math.cos(t) + bump,
               3000.0 + 300.0 * math.sin(t),
               1500.0 + 5.0 * i)
        pts.append(struct.unpack("<3f", struct.pack("<3f", *xyz)))
    return pts


def e2e_velocities(pts):
    """Central difference inside a segment, one-sided over ONE tick at the ends.
    Reproduced here rather than asked for, because the JSON has to carry a
    velocity that matches one of these to within MARKER_TOL before the reference
    will place a marker at all -- so getting it wrong shows up as markers_ok 0
    in the assertions below rather than as a fixture nobody checked."""
    n = len(pts)
    out = []
    for i in range(n):
        if i == 0:
            a, b, span = pts[0], pts[1], 1
        elif i == n - 1:
            a, b, span = pts[n - 2], pts[n - 1], 1
        else:
            a, b, span = pts[i - 1], pts[i + 1], 2
        d = span * E2E_DT
        out.append(((b[0] - a[0]) / d, (b[1] - a[1]) / d, (b[2] - a[2]) / d))
    return out


def e2e_body():
    import struct
    body = bytearray(b"\xFF" * E2E_BODY)
    for i, p in enumerate(e2e_points()):
        at = 0x300 + i * E2E_STRIDE
        body[at:at + 12] = struct.pack("<3f", *p)
    return bytes(body)


def e2e_mtv(js_text):
    """The same container mtv() builds, at the v2 JSON offset, but carrying a
    body with a route in it and whatever run-stats JSON it is handed."""
    import struct
    json_at = 0xC7
    head = bytearray(b"\0" * json_at)
    head[0:4] = b"MMTV"
    struct.pack_into("<I", head, 0x04, 2)
    struct.pack_into("<q", head, 0x08, MTV_DATE_MS)
    head[0x10:0x10 + len(E2E_MAP)] = E2E_MAP.encode()
    head[0x50:0x50 + len(MTV_HASH)] = MTV_HASH.encode()
    head[0x79] = 1                                  # gamemode: surf
    struct.pack_into("<f", head, 0x7B, E2E_DT)
    struct.pack_into("<Q", head, 0x7F, E2E_STEAMID)
    head[0x87:0x87 + len(MTV_PLAYER)] = MTV_PLAYER.encode()
    head[0xA7] = 0                                  # track type: main
    head[0xA8] = 1                                  # track num
    struct.pack_into("<d", head, 0xA9, E2E_RUN_TIME)
    struct.pack_into("<I", head, 0xB1, E2E_TICKS)

    blob = js_text.encode("utf-8")
    struct.pack_into("<I", head, json_at - 4, len(blob))

    data = e2e_body()
    props, comp = valve_lzma(data)

    out = bytearray(head)
    out += blob
    out += b"LZMA"
    out += struct.pack("<II", len(data), len(comp))
    out += props
    out += comp
    assert out.index(b"{", 0xB0) == json_at
    return bytes(out)


def run_reference(mtv_bytes, work, extra):
    """Write the demo where the reference will find it and run it. Returns the
    parsed --dump-info row, and the .wrpath if one was written."""
    import subprocess
    ref = os.path.join(HERE, "reference", "wrpath_extract.py")
    game = os.path.join(work, "game")
    demo = os.path.join(game, "momentum", "momtv", "online", "1",
                        E2E_STEM + ".mtv")
    os.makedirs(os.path.dirname(demo), exist_ok=True)
    with open(demo, "wb") as f:
        f.write(mtv_bytes)

    env = dict(os.environ, WRLINES_FAKE_NOW=E2E_FAKE_NOW)
    info = os.path.join(work, "info.tsv")
    subprocess.run([sys.executable, ref, "--game", game, "--file", demo,
                    "--dump-info", info], check=True, env=env,
                   stdout=subprocess.DEVNULL)
    with open(info, "r", encoding="utf-8") as f:
        head = f.readline().rstrip("\n").split("\t")
        row = dict(zip(head, f.readline().rstrip("\n").split("\t")))

    written = None
    if extra:
        out = os.path.join(work, "out")
        subprocess.run([sys.executable, ref, "--game", game, "--file", demo,
                        "--out", out], check=True, env=env,
                       stdout=subprocess.DEVNULL)
        p = os.path.join(out, E2E_MAP, E2E_STEM + ".wrpath")
        with open(p, "rb") as f:
            written = f.read()
    os.remove(demo)
    return row, written


def e2e():
    """Two passes. The first learns what the reference makes of the body with
    no run stats at all; the second hands those numbers back to it as the JSON,
    so the fixture asks the speed oracle to confirm a chain rather than skipping
    it -- which is the single most load-bearing thing extract_path does, and the
    thing a fixture with no maxHorizontalSpeed would never exercise."""
    import shutil
    import tempfile

    work = tempfile.mkdtemp(prefix="wrlines-e2e-")
    try:
        first, _ = run_reference(e2e_mtv("{}"), work, extra=False)
        assert first["status"] == "ok", first
        speed = float(first["chain_max_horiz"])
        assert first["identified_by"] == "speed", first

        pts = e2e_points()
        vel = e2e_velocities(pts)
        sv = vel[E2E_START_AT]
        mv = vel[E2E_MARKER_AT]

        js = {
            "trackStats": {"maxHorizontalSpeed": speed},
            "segments": [{
                "effectiveStartVelocity": [sv[0], sv[1], sv[2]],
                "subsegments": [{
                    "minorNum": 1,
                    "timeReached": E2E_MARKER_AT * E2E_DT,
                    "velocityWhenReached": [mv[0], mv[1], mv[2]],
                    "stats": {"maxOverallSpeed": speed},
                }],
            }],
        }
        # repr, not %.6f: the velocity is matched against a central difference
        # to a relative 8%, but maxHorizontalSpeed is compared to 0.5% and a
        # rounded one would put the fixture on the edge of its own tolerance.
        text = json.dumps(js, separators=(",", ":"))
        blob = e2e_mtv(text)

        row, wrpath = run_reference(blob, work, extra=True)

        # What the fixture is FOR. Every one of these is a distinct arm of the
        # pipeline, and a golden that matched byte for byte while any of them
        # had gone quiet would be proving much less than it looks like.
        assert row["status"] == "ok", row
        assert row["identified_by"] == "speed", row
        assert row["confident"] == "1", row
        assert row["segments"] == "1", row
        assert int(row["samples"]) == E2E_POINTS, row
        assert row["markers"] == "1" and row["markers_ok"] == "1", row
        assert row["start_ok"] == "1", row
        assert int(row["start_index"]) == E2E_START_AT, row
        assert float(row["match_error"]) < 1e-9, row
        assert row["flagged"] == "0", row
        return blob, wrpath, text, row
    finally:
        shutil.rmtree(work, ignore_errors=True)


# ---------------------------------------------------------------------------

if __name__ == "__main__":
    write_header(
        "fixture_msml.h", "WR_FIXTURE_MSML_H",
        "Two map-cache files, as momentum\\_cache holds them: four bytes of\n"
        "magic, the decompressed size, the map count, and a raw zlib stream.",
        [carray("kApprovedDat", msml(APPROVED)),
         carray("kSubmissionDat", msml(SUBMISSION))])

    # 16 KB, not 64. Big enough that the 1000-byte back-references are well
    # inside it and the encoder has to emit long-distance matches; small enough
    # that the committed array stays around sixty kilobytes of text.
    big = payload(16384)
    props, comp = valve_lzma(big)
    assert props == bytes([0x5D, 0x00, 0x00, 0x01, 0x00]), props.hex()
    write_header(
        "fixture_lzma.h", "WR_FIXTURE_LZMA_H",
        "One raw LZMA1 stream of %d bytes of Payload(), and the five property\n"
        "bytes that go with it. lc=3 lp=0 pb=2 is 0x5D, the default every LZMA\n"
        "encoder writes; dict_size is 64 KB, which is the smallest that still\n"
        "covers the 1000-byte back-references the payload is built to contain."
        % len(big),
        ["#define WR_FIXTURE_LZMA_RAW %d" % len(big),
         carray("kLzmaProps", props),
         carray("kLzmaStream", comp)])

    write_header(
        "fixture_mtv.h", "WR_FIXTURE_MTV_H",
        "Three synthetic demos of the same run. Two differ only in where the\n"
        "run-stats JSON starts -- 0xC6 as the v1 container puts it, 0xC7 as v2\n"
        "does -- and carry %d bytes of Payload() as a Valve-LZMA body.\n"
        "\n"
        "The third is that same run with a zstd body, and it is not the same\n"
        "container with one field changed: a zstd demo has no Valve header at\n"
        "all, so the frame magic sits exactly where \"LZMA\" would and the\n"
        "twenty-two bytes of lengths and properties behind it are absent. Its\n"
        "size therefore differs from the other two, which is why the harness\n"
        "cannot share one length constant." % MTV_BODY_BYTES,
        ["#define WR_FIXTURE_MTV_BODY %d" % MTV_BODY_BYTES,
         "#define WR_FIXTURE_MTV_JSON_V1 0xC6",
         "#define WR_FIXTURE_MTV_JSON_V2 0xC7",
         '#define WR_FIXTURE_MTV_JSON_LEN %d' % len(MTV_JSON),
         carray("kMtvV1", mtv(0xC6)),
         carray("kMtvV2", mtv(0xC7)),
         carray("kMtvZstd", mtv(0xC6, codec="zstd"))])

    zbody = payload(16384)
    write_header(
        "fixture_zstd.h", "WR_FIXTURE_ZSTD_H",
        "One zstd frame of %d bytes of Payload(), written with an explicit\n"
        "content size -- which is not decoration. A frame that declines to say\n"
        "how big it is cannot be decoded one-shot by either implementation:\n"
        "python-zstandard raises and WrMtvZstdSize refuses by name. Every demo\n"
        "in the wild carries one.\n"
        "\n"
        "The same Payload() as fixture_lzma.h, deliberately, so the two\n"
        "harnesses compare their decoders against one set of expected bytes\n"
        "derived by formula rather than against each other." % len(zbody),
        ["#define WR_FIXTURE_ZSTD_RAW %d" % len(zbody),
         carray("kZstdFrame", valve_zstd(zbody))])

    blob, wrpath, text, row = e2e()
    write_header(
        "fixture_e2e.h", "WR_FIXTURE_E2E_H",
        "One whole synthetic demo and the .wrpath wrpath_extract.py wrote from\n"
        "it, with WRLINES_FAKE_NOW pinned at %s so the header stamp the CRC\n"
        "covers is a constant.\n"
        "\n"
        "The body is %d bytes of 0xFF with %d coordinate triples planted every\n"
        "%d bytes from 0x300 -- a gentle helix, one deliberately doubled step\n"
        "at the halfway mark. The run stats were then written to MATCH what the\n"
        "reference made of that body, so the fixture exercises the speed oracle\n"
        "rather than skipping it:\n"
        "\n"
        "%s\n"
        "\n"
        "The reference reported: %d candidates, %d points, coverage %s,\n"
        "identified by %s, match error %s, start at index %s, 1 marker placed."
        % (E2E_FAKE_NOW, E2E_BODY, E2E_POINTS, E2E_STRIDE,
           "\n".join("    " + text[i:i + 68] for i in range(0, len(text), 68)),
           int(row["candidates"]), int(row["samples"]), row["coverage"],
           row["identified_by"], row["match_error"], row["start_index"]),
        ["#define WR_FIXTURE_E2E_MAP \"%s\"" % E2E_MAP,
         "#define WR_FIXTURE_E2E_STEM \"%s\"" % E2E_STEM,
         "#define WR_FIXTURE_E2E_NOW \"%s\"" % E2E_FAKE_NOW,
         "#define WR_FIXTURE_E2E_POINTS %d" % E2E_POINTS,
         "#define WR_FIXTURE_E2E_START %d" % E2E_START_AT,
         carray("kE2eMtv", blob),
         carray("kE2eWrpath", wrpath)])
