# make_fixture.py  --  generate the committed test fixtures.
#
# Run by hand, never by tests\build.bat and never by CI:
#
#     py -3 tests\make_fixture.py
#
# It writes tests\fixture_msml.h, tests\fixture_lzma.h and tests\fixture_mtv.h,
# which are committed. Re-run and commit the result if a fixture needs to grow
# a case.
#
# WHY THE BYTES ARE COMMITTED RATHER THAN MADE AT RUN TIME
#
# The build deliberately has no compressor of any kind. miniz comes in with
# MINIZ_NO_DEFLATE_APIS, and of the LZMA SDK only the decoder is vendored --
# 39 KB of the 400-odd files in the archive. So a harness that wants a
# compressed stream to read cannot make one; it has to be handed the bytes.
# That is a good property to keep, and this script is the price of it.
#
# THE FIXTURES ARE SYNTHETIC ON PURPOSE
#
# A slice of the real momentum\_cache, or a real demo, would be simpler and is
# not an option: both are other people's work with real ids in them, and the
# repository already refuses to carry anything of that shape (see .gitignore's
# reasoning about demos). Everything below is invented, and chosen to hit the
# paths that are otherwise only reachable on a machine with a game installed.

import json
import lzma
import os
import zlib

HERE = os.path.dirname(os.path.abspath(__file__))


# ---------------------------------------------------------------------------
# Writing a header
# ---------------------------------------------------------------------------

def carray(name, blob):
    out = ["static const unsigned char %s[%d] = {" % (name, len(blob))]
    for i in range(0, len(blob), 12):
        out.append("    %s," % ", ".join("0x%02x" % b for b in blob[i:i + 12]))
    out.append("};")
    return "\n".join(out)


def write_header(name, guard, why, parts):
    path = os.path.join(HERE, name)
    body = ["// %s  --  generated by tests\\make_fixture.py. Do not hand-edit." % name,
            "//"]
    body += ["// " + line if line else "//" for line in why.strip().split("\n")]
    body += ["", "#ifndef %s" % guard, "#define %s" % guard, ""]
    for part in parts:
        body.append(part)
        body.append("")
    body += ["#endif // %s" % guard, ""]
    with open(path, "w", encoding="utf-8", newline="\n") as f:
        f.write("\n".join(body))
    print("wrote %s" % path)


# ---------------------------------------------------------------------------
# The map cache
# ---------------------------------------------------------------------------
#
#   - "tier": null, which a submitted map has until somebody rates it
#   - an id that is a JSON float, which the reference skips because it tests
#     isinstance(mid, int) and 265.0 is not one
#   - a tier on a trackType 1 board, which must NOT become the map's tier
#   - gamemodes listed out of order, which must come out sorted
#   - the same map name in both files, where the later file has to win
#   - a non-ASCII name, which must come out as the same UTF-8 bytes
#   - an object-with-"maps" file rather than a bare array, the branch the
#     reference keeps for a shape we have never actually met

APPROVED = [
    {"id": 383, "name": "bhop_landmark2",
     "leaderboards": [
         {"gamemode": 2, "trackType": 0, "trackNum": 1, "tier": 2},
         {"gamemode": 1, "trackType": 0, "trackNum": 1, "tier": 2},
         {"gamemode": 2, "trackType": 1, "trackNum": 1, "tier": 7},
     ]},
    # Overwritten by the submission file below: this is the stale copy.
    {"id": 111, "name": "surf_overlap",
     "leaderboards": [{"gamemode": 1, "trackType": 0, "trackNum": 1, "tier": 1}]},
    # No leaderboards at all: tier 0, no modes, and still a valid row.
    {"id": 7, "name": "ahop_bare", "leaderboards": []},
    # Not an int id. Skipped entirely, as isinstance(mid, int) skips it.
    {"id": 265.0, "name": "surf_floatid",
     "leaderboards": [{"gamemode": 1, "trackType": 0, "trackNum": 1, "tier": 3}]},
]

SUBMISSION = {"maps": [
    # Wins over the approved copy above, and is therefore NOT approved.
    {"id": 112, "name": "surf_overlap",
     "leaderboards": [{"gamemode": 1, "trackType": 0, "trackNum": 1, "tier": 5}]},
    # Unrated, which is null rather than absent.
    {"id": 1816, "name": "bhop_luvinox",
     "leaderboards": [{"gamemode": 2, "trackType": 0, "trackNum": 1,
                       "tier": None}]},
    # Modes deliberately descending in the file; the index is sorted.
    {"id": 900, "name": "surf_modes",
     "leaderboards": [
         {"gamemode": 12, "trackType": 0, "trackNum": 1, "tier": 4},
         {"gamemode": 3,  "trackType": 0, "trackNum": 1, "tier": 4},
         {"gamemode": 7,  "trackType": 2, "trackNum": 1, "tier": 9},
     ]},
    {"id": 901, "name": "surf_ümläut",
     "leaderboards": [{"gamemode": 1, "trackType": 0, "trackNum": 1, "tier": 6}]},
]}


def msml(obj):
    """MSML, u32 decompressed size, u32 map count, then a raw zlib stream."""
    maps = obj if isinstance(obj, list) else obj["maps"]
    body = json.dumps(obj, separators=(",", ":"), ensure_ascii=False)
    body = body.encode("utf-8")
    out = bytearray(b"MSML")
    out += len(body).to_bytes(4, "little")
    out += len(maps).to_bytes(4, "little")
    out += zlib.compress(body, 9)
    return bytes(out)


# ---------------------------------------------------------------------------
# A payload worth compressing
# ---------------------------------------------------------------------------
#
# Written as a formula rather than as bytes so that the committed header holds
# only the COMPRESSED stream. The harness computes the expected output with the
# same twelve lines and compares, which is what makes "the decoder produced the
# right bytes" a real assertion rather than "the decoder produced the bytes
# next to it in the same file".
#
# It has to be worth compressing in the specific ways the decoder can get
# wrong, so it is three things interleaved: literals it cannot predict, short
# runs of one byte, and matches a thousand bytes back. A decoder that mishandles
# long distances passes on noise alone.
#
# Keep in step with Payload() in tests\test_lzma.cpp and tests\test_mtv.cpp.

def payload(n):
    out = bytearray()
    s = 12345
    for i in range(n):
        s = (s * 1664525 + 1013904223) & 0xFFFFFFFF
        if i >= 1000 and (i // 137) % 3 == 0:
            out.append(out[i - 1000])
        elif (i // 61) % 5 == 0:
            out.append(0x41)
        else:
            out.append((s >> 24) & 0xFF)
    return bytes(out)


def valve_lzma(data, lc=3, lp=0, pb=2, dict_size=1 << 16):
    """The five property bytes and a raw LZMA1 stream, as a .mtv carries them."""
    filt = [{"id": lzma.FILTER_LZMA1, "lc": lc, "lp": lp, "pb": pb,
             "dict_size": dict_size}]
    c = lzma.LZMACompressor(format=lzma.FORMAT_RAW, filters=filt)
    comp = c.compress(data) + c.flush()

    props = bytes([(pb * 5 + lp) * 9 + lc]) + dict_size.to_bytes(4, "little")

    # Decode it back exactly the way wrpath_extract.py's decompress_body does,
    # so a fixture that the reference cannot read never reaches the repository.
    d = lzma.LZMADecompressor(format=lzma.FORMAT_RAW, filters=filt)
    back = d.decompress(comp, len(data))
    assert back == data, "fixture does not round-trip through the reference"
    return props, comp


# ---------------------------------------------------------------------------
# A demo
# ---------------------------------------------------------------------------
#
# The whole container, at both of the JSON offsets seen in the wild. The two
# differ by one byte of padding, which is the entire reason the reference
# locates the blob by scanning instead of reading it from a constant -- so a
# fixture that only had one of them would not test the thing the scan exists
# for.
#
# The run-stats JSON is deliberately FLAT, with no nested object, so that the
# first '{' at or after 0xB0 is the real one. The compressed body begins inside
# the same window and contains braces of its own, which is true of every real
# demo too -- the locator's job is to stop at the first one that validates, and
# a fixture where no other candidate existed would not be asking it to.

MTV_MAP = "surf_fixture"
MTV_HASH = "0123456789abcdef0123456789abcdef01234567"
MTV_PLAYER = "fixture player"
MTV_STEAMID = 0x0110000112345678
MTV_DATE_MS = 1700000000123
MTV_TICKS = 4083
MTV_BODY_BYTES = 4096

MTV_JSON = ('{"maxHorizontalSpeed":2500.5,"effectiveStartVelocity":320.25,'
            '"jumps":41,"strafes":812,"note":"synthetic, see make_fixture.py"}')


def mtv(json_at):
    import struct
    head = bytearray(b"\0" * json_at)
    head[0:4] = b"MMTV"
    struct.pack_into("<I", head, 0x04, 2)
    struct.pack_into("<q", head, 0x08, MTV_DATE_MS)
    head[0x10:0x10 + len(MTV_MAP)] = MTV_MAP.encode()
    head[0x50:0x50 + len(MTV_HASH)] = MTV_HASH.encode()
    head[0x79] = 1                                  # gamemode: surf
    struct.pack_into("<f", head, 0x7B, 0.015)
    struct.pack_into("<Q", head, 0x7F, MTV_STEAMID)
    head[0x87:0x87 + len(MTV_PLAYER)] = MTV_PLAYER.encode()
    head[0xA7] = 2                                  # track type: bonus
    head[0xA8] = 3                                  # track num
    struct.pack_into("<d", head, 0xA9, 61.25)
    struct.pack_into("<I", head, 0xB1, MTV_TICKS)

    blob = MTV_JSON.encode()
    struct.pack_into("<I", head, json_at - 4, len(blob))

    data = payload(MTV_BODY_BYTES)
    props, comp = valve_lzma(data)

    out = bytearray(head)
    out += blob
    out += b"LZMA"
    out += struct.pack("<II", len(data), len(comp))
    out += props
    out += comp

    # The promises the harness is written against. Note what is NOT promised:
    # that there is only one '{' in the window. The compressed body starts well
    # before 0x200 and a compressed stream contains whatever bytes it contains,
    # exactly as a real demo's does. What matters is that the FIRST brace at or
    # after 0xB0 is the real one, so the locator stops on it and the padding
    # before it holds none.
    assert len(out) >= 0x200
    assert out.index(b"{", 0xB0) == json_at
    return bytes(out)


# ---------------------------------------------------------------------------

if __name__ == "__main__":
    write_header(
        "fixture_msml.h", "WR_FIXTURE_MSML_H",
        "Two map-cache files, as momentum\\_cache holds them: four bytes of\n"
        "magic, the decompressed size, the map count, and a raw zlib stream.",
        [carray("kApprovedDat", msml(APPROVED)),
         carray("kSubmissionDat", msml(SUBMISSION))])

    # 16 KB, not 64. Big enough that the 1000-byte back-references are well
    # inside it and the encoder has to emit long-distance matches; small enough
    # that the committed array stays around sixty kilobytes of text.
    big = payload(16384)
    props, comp = valve_lzma(big)
    assert props == bytes([0x5D, 0x00, 0x00, 0x01, 0x00]), props.hex()
    write_header(
        "fixture_lzma.h", "WR_FIXTURE_LZMA_H",
        "One raw LZMA1 stream of %d bytes of Payload(), and the five property\n"
        "bytes that go with it. lc=3 lp=0 pb=2 is 0x5D, the default every LZMA\n"
        "encoder writes; dict_size is 64 KB, which is the smallest that still\n"
        "covers the 1000-byte back-references the payload is built to contain."
        % len(big),
        ["#define WR_FIXTURE_LZMA_RAW %d" % len(big),
         carray("kLzmaProps", props),
         carray("kLzmaStream", comp)])

    write_header(
        "fixture_mtv.h", "WR_FIXTURE_MTV_H",
        "Two synthetic demos, identical but for where the run-stats JSON\n"
        "starts: 0xC6 as the v1 container puts it, 0xC7 as v2 does. Both carry\n"
        "%d bytes of Payload() as a Valve-LZMA body." % MTV_BODY_BYTES,
        ["#define WR_FIXTURE_MTV_BODY %d" % MTV_BODY_BYTES,
         "#define WR_FIXTURE_MTV_JSON_V1 0xC6",
         "#define WR_FIXTURE_MTV_JSON_V2 0xC7",
         '#define WR_FIXTURE_MTV_JSON_LEN %d' % len(MTV_JSON),
         carray("kMtvV1", mtv(0xC6)),
         carray("kMtvV2", mtv(0xC7))])
